Repository Drone3D-Team/Drone3D, pull requests merged in 2021-05, with the labels that each got.

#211 Fix create itinerary activity bug
  app/src/main/java/ch/epfl/sdp/drone3d/map/gps/LocationComponentManager.kt
Labels: bug

#214 Log toasts when they are displayed
  app/src/main/java/ch/epfl/sdp/drone3d/ui/ToastHandler.kt
Labels: actual: 5m

#316 Close keyboard when drone connect
  app/src/androidTest/java/ch/epfl/sdp/drone3d/ui/mission/ItineraryCreateActivityTest.kt
  app/src/main/java/ch/epfl/sdp/drone3d/ui/Utils.kt
  app/src/main/java/ch/epfl/sdp/drone3d/ui/auth/LoginActivity.kt
  app/src/main/java/ch/epfl/sdp/drone3d/ui/auth/RegisterActivity.kt
  app/src/main/java/ch/epfl/sdp/drone3d/ui/drone/DroneConnectActivity.kt
  app/src/main/res/layout/activity_drone_connect.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
Labels: actual: 1h30

#315 Let the user be far from the "drone" when it is simulated
  app/src/androidTest/java/ch/epfl/sdp/drone3d/ui/map/MissionInProgressActivityTest.kt
  app/src/main/java/ch/epfl/sdp/drone3d/ui/map/MissionInProgressActivity.kt
Labels: actual: 1h
